# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: GGI
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Resiliency - Human Security - Emergency Preparedness
baseurl: /SecondaryCities2
url: "http://yourdomain.com" # the base hostname & protocol for your site

# Social media profiles - feel free to add more here
#twitter_username: SBootstrap
github_username:  state-hiu
#facebook_username: StartBootstrap
e-mail_address: HIU_INFO@state.gov

# Build settings
markdown: kramdown

# saves time with compilling jekyll
# http://stackoverflow.com/questions/26855552/jekyll-compiling-seems-way-too-slow
exclude: [node_modules]
